/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MultiClusterDslUiModule extends AbstractMultiClusterDslUiModule {

	public MultiClusterDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
