/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMultiClusterDslScopeProvider extends DelegatingScopeProvider {
}
