/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MultiClusterDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "multicluster.dsl.MultiClusterDsl.Model");
		private final Assignment cApplicationAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cApplicationApplicationParserRuleCall_0 = (RuleCall)cApplicationAssignment.eContents().get(0);
		
		////Model:
		////    greetings+=Greeting*;
		////
		////Greeting:
		////    'Hello' name=ID '!';
		//Model:
		//application=Application
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//application=Application
		public Assignment getApplicationAssignment() { return cApplicationAssignment; }
		
		//Application
		public RuleCall getApplicationApplicationParserRuleCall_0() { return cApplicationApplicationParserRuleCall_0; }
	}
	public class ApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "multicluster.dsl.MultiClusterDsl.Application");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplicationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cClustersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cClustersClusterParserRuleCall_3_0 = (RuleCall)cClustersAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Application:
		//'application' name=ID '{'
		//clusters+=Cluster*
		//'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'application' name=ID '{'
		//clusters+=Cluster*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'application'
		public Keyword getApplicationKeyword_0() { return cApplicationKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//clusters+=Cluster*
		public Assignment getClustersAssignment_3() { return cClustersAssignment_3; }
		
		//Cluster
		public RuleCall getClustersClusterParserRuleCall_3_0() { return cClustersClusterParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ClusterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "multicluster.dsl.MultiClusterDsl.Cluster");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClusterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDeploymentAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDeploymentDeploymentParserRuleCall_3_0 = (RuleCall)cDeploymentAssignment_3.eContents().get(0);
		private final Assignment cIngressAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIngressIngressParserRuleCall_4_0 = (RuleCall)cIngressAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Cluster:
		//'cluster' name=ID '{'
		//deployment=Deployment
		//ingress=Ingress?
		//'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'cluster' name=ID '{'
		//deployment=Deployment
		//ingress=Ingress?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'cluster'
		public Keyword getClusterKeyword_0() { return cClusterKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//deployment=Deployment
		public Assignment getDeploymentAssignment_3() { return cDeploymentAssignment_3; }
		
		//Deployment
		public RuleCall getDeploymentDeploymentParserRuleCall_3_0() { return cDeploymentDeploymentParserRuleCall_3_0; }
		
		//ingress=Ingress?
		public Assignment getIngressAssignment_4() { return cIngressAssignment_4; }
		
		//Ingress
		public RuleCall getIngressIngressParserRuleCall_4_0() { return cIngressIngressParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class DeploymentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "multicluster.dsl.MultiClusterDsl.Deployment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDeploymentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cImageKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cImageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImageSTRINGTerminalRuleCall_3_0 = (RuleCall)cImageAssignment_3.eContents().get(0);
		private final Keyword cReplicasKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cReplicasAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cReplicasINTTerminalRuleCall_5_0 = (RuleCall)cReplicasAssignment_5.eContents().get(0);
		private final Assignment cResourcesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cResourcesResourcesParserRuleCall_6_0 = (RuleCall)cResourcesAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Deployment:
		//'deployment' '{'
		//'image' image=STRING
		//'replicas' replicas=INT
		//resources=Resources
		//'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'deployment' '{'
		//'image' image=STRING
		//'replicas' replicas=INT
		//resources=Resources
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'deployment'
		public Keyword getDeploymentKeyword_0() { return cDeploymentKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'image'
		public Keyword getImageKeyword_2() { return cImageKeyword_2; }
		
		//image=STRING
		public Assignment getImageAssignment_3() { return cImageAssignment_3; }
		
		//STRING
		public RuleCall getImageSTRINGTerminalRuleCall_3_0() { return cImageSTRINGTerminalRuleCall_3_0; }
		
		//'replicas'
		public Keyword getReplicasKeyword_4() { return cReplicasKeyword_4; }
		
		//replicas=INT
		public Assignment getReplicasAssignment_5() { return cReplicasAssignment_5; }
		
		//INT
		public RuleCall getReplicasINTTerminalRuleCall_5_0() { return cReplicasINTTerminalRuleCall_5_0; }
		
		//resources=Resources
		public Assignment getResourcesAssignment_6() { return cResourcesAssignment_6; }
		
		//Resources
		public RuleCall getResourcesResourcesParserRuleCall_6_0() { return cResourcesResourcesParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ResourcesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "multicluster.dsl.MultiClusterDsl.Resources");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCpuKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCpuAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCpuSTRINGTerminalRuleCall_3_0 = (RuleCall)cCpuAssignment_3.eContents().get(0);
		private final Keyword cMemoryKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMemoryAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMemorySTRINGTerminalRuleCall_5_0 = (RuleCall)cMemoryAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Resources:
		//'resources' '{'
		//'cpu' cpu=STRING
		//'memory' memory=STRING
		//'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'resources' '{'
		//'cpu' cpu=STRING
		//'memory' memory=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'resources'
		public Keyword getResourcesKeyword_0() { return cResourcesKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'cpu'
		public Keyword getCpuKeyword_2() { return cCpuKeyword_2; }
		
		//cpu=STRING
		public Assignment getCpuAssignment_3() { return cCpuAssignment_3; }
		
		//STRING
		public RuleCall getCpuSTRINGTerminalRuleCall_3_0() { return cCpuSTRINGTerminalRuleCall_3_0; }
		
		//'memory'
		public Keyword getMemoryKeyword_4() { return cMemoryKeyword_4; }
		
		//memory=STRING
		public Assignment getMemoryAssignment_5() { return cMemoryAssignment_5; }
		
		//STRING
		public RuleCall getMemorySTRINGTerminalRuleCall_5_0() { return cMemorySTRINGTerminalRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class IngressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "multicluster.dsl.MultiClusterDsl.Ingress");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIngressKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPathKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPathAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPathSTRINGTerminalRuleCall_3_0 = (RuleCall)cPathAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Ingress:
		//'ingress' '{'
		//'path' path=STRING
		//'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'ingress' '{'
		//'path' path=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ingress'
		public Keyword getIngressKeyword_0() { return cIngressKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'path'
		public Keyword getPathKeyword_2() { return cPathKeyword_2; }
		
		//path=STRING
		public Assignment getPathAssignment_3() { return cPathAssignment_3; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_3_0() { return cPathSTRINGTerminalRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private final ModelElements pModel;
	private final ApplicationElements pApplication;
	private final ClusterElements pCluster;
	private final DeploymentElements pDeployment;
	private final ResourcesElements pResources;
	private final IngressElements pIngress;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MultiClusterDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pApplication = new ApplicationElements();
		this.pCluster = new ClusterElements();
		this.pDeployment = new DeploymentElements();
		this.pResources = new ResourcesElements();
		this.pIngress = new IngressElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("multicluster.dsl.MultiClusterDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////Model:
	////    greetings+=Greeting*;
	////
	////Greeting:
	////    'Hello' name=ID '!';
	//Model:
	//application=Application
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Application:
	//'application' name=ID '{'
	//clusters+=Cluster*
	//'}'
	//;
	public ApplicationElements getApplicationAccess() {
		return pApplication;
	}
	
	public ParserRule getApplicationRule() {
		return getApplicationAccess().getRule();
	}
	
	//Cluster:
	//'cluster' name=ID '{'
	//deployment=Deployment
	//ingress=Ingress?
	//'}'
	//;
	public ClusterElements getClusterAccess() {
		return pCluster;
	}
	
	public ParserRule getClusterRule() {
		return getClusterAccess().getRule();
	}
	
	//Deployment:
	//'deployment' '{'
	//'image' image=STRING
	//'replicas' replicas=INT
	//resources=Resources
	//'}'
	//;
	public DeploymentElements getDeploymentAccess() {
		return pDeployment;
	}
	
	public ParserRule getDeploymentRule() {
		return getDeploymentAccess().getRule();
	}
	
	//Resources:
	//'resources' '{'
	//'cpu' cpu=STRING
	//'memory' memory=STRING
	//'}'
	//;
	public ResourcesElements getResourcesAccess() {
		return pResources;
	}
	
	public ParserRule getResourcesRule() {
		return getResourcesAccess().getRule();
	}
	
	//Ingress:
	//'ingress' '{'
	//'path' path=STRING
	//'}'
	//;
	public IngressElements getIngressAccess() {
		return pIngress;
	}
	
	public ParserRule getIngressRule() {
		return getIngressAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
