/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl.impl;

import multicluster.dsl.multiClusterDsl.AutoScaling;
import multicluster.dsl.multiClusterDsl.MultiClusterDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Auto Scaling</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.AutoScalingImpl#getMinReplicas <em>Min Replicas</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.AutoScalingImpl#getMaxReplicas <em>Max Replicas</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.AutoScalingImpl#getCpuUtilization <em>Cpu Utilization</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AutoScalingImpl extends MinimalEObjectImpl.Container implements AutoScaling
{
  /**
   * The default value of the '{@link #getMinReplicas() <em>Min Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinReplicas()
   * @generated
   * @ordered
   */
  protected static final int MIN_REPLICAS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMinReplicas() <em>Min Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinReplicas()
   * @generated
   * @ordered
   */
  protected int minReplicas = MIN_REPLICAS_EDEFAULT;

  /**
   * The default value of the '{@link #getMaxReplicas() <em>Max Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxReplicas()
   * @generated
   * @ordered
   */
  protected static final int MAX_REPLICAS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaxReplicas() <em>Max Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxReplicas()
   * @generated
   * @ordered
   */
  protected int maxReplicas = MAX_REPLICAS_EDEFAULT;

  /**
   * The default value of the '{@link #getCpuUtilization() <em>Cpu Utilization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCpuUtilization()
   * @generated
   * @ordered
   */
  protected static final int CPU_UTILIZATION_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCpuUtilization() <em>Cpu Utilization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCpuUtilization()
   * @generated
   * @ordered
   */
  protected int cpuUtilization = CPU_UTILIZATION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AutoScalingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MultiClusterDslPackage.Literals.AUTO_SCALING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMinReplicas()
  {
    return minReplicas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMinReplicas(int newMinReplicas)
  {
    int oldMinReplicas = minReplicas;
    minReplicas = newMinReplicas;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.AUTO_SCALING__MIN_REPLICAS, oldMinReplicas, minReplicas));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMaxReplicas()
  {
    return maxReplicas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaxReplicas(int newMaxReplicas)
  {
    int oldMaxReplicas = maxReplicas;
    maxReplicas = newMaxReplicas;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.AUTO_SCALING__MAX_REPLICAS, oldMaxReplicas, maxReplicas));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCpuUtilization()
  {
    return cpuUtilization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCpuUtilization(int newCpuUtilization)
  {
    int oldCpuUtilization = cpuUtilization;
    cpuUtilization = newCpuUtilization;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.AUTO_SCALING__CPU_UTILIZATION, oldCpuUtilization, cpuUtilization));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.AUTO_SCALING__MIN_REPLICAS:
        return getMinReplicas();
      case MultiClusterDslPackage.AUTO_SCALING__MAX_REPLICAS:
        return getMaxReplicas();
      case MultiClusterDslPackage.AUTO_SCALING__CPU_UTILIZATION:
        return getCpuUtilization();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.AUTO_SCALING__MIN_REPLICAS:
        setMinReplicas((Integer)newValue);
        return;
      case MultiClusterDslPackage.AUTO_SCALING__MAX_REPLICAS:
        setMaxReplicas((Integer)newValue);
        return;
      case MultiClusterDslPackage.AUTO_SCALING__CPU_UTILIZATION:
        setCpuUtilization((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.AUTO_SCALING__MIN_REPLICAS:
        setMinReplicas(MIN_REPLICAS_EDEFAULT);
        return;
      case MultiClusterDslPackage.AUTO_SCALING__MAX_REPLICAS:
        setMaxReplicas(MAX_REPLICAS_EDEFAULT);
        return;
      case MultiClusterDslPackage.AUTO_SCALING__CPU_UTILIZATION:
        setCpuUtilization(CPU_UTILIZATION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.AUTO_SCALING__MIN_REPLICAS:
        return minReplicas != MIN_REPLICAS_EDEFAULT;
      case MultiClusterDslPackage.AUTO_SCALING__MAX_REPLICAS:
        return maxReplicas != MAX_REPLICAS_EDEFAULT;
      case MultiClusterDslPackage.AUTO_SCALING__CPU_UTILIZATION:
        return cpuUtilization != CPU_UTILIZATION_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (minReplicas: ");
    result.append(minReplicas);
    result.append(", maxReplicas: ");
    result.append(maxReplicas);
    result.append(", cpuUtilization: ");
    result.append(cpuUtilization);
    result.append(')');
    return result.toString();
  }

} //AutoScalingImpl
