/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl.impl;

import multicluster.dsl.multiClusterDsl.Cluster;
import multicluster.dsl.multiClusterDsl.Deployment;
import multicluster.dsl.multiClusterDsl.Ingress;
import multicluster.dsl.multiClusterDsl.MultiClusterDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cluster</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.ClusterImpl#getName <em>Name</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.ClusterImpl#getDeployment <em>Deployment</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.ClusterImpl#getIngress <em>Ingress</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClusterImpl extends MinimalEObjectImpl.Container implements Cluster
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDeployment() <em>Deployment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeployment()
   * @generated
   * @ordered
   */
  protected Deployment deployment;

  /**
   * The cached value of the '{@link #getIngress() <em>Ingress</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIngress()
   * @generated
   * @ordered
   */
  protected Ingress ingress;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClusterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MultiClusterDslPackage.Literals.CLUSTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.CLUSTER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Deployment getDeployment()
  {
    return deployment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDeployment(Deployment newDeployment, NotificationChain msgs)
  {
    Deployment oldDeployment = deployment;
    deployment = newDeployment;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.CLUSTER__DEPLOYMENT, oldDeployment, newDeployment);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeployment(Deployment newDeployment)
  {
    if (newDeployment != deployment)
    {
      NotificationChain msgs = null;
      if (deployment != null)
        msgs = ((InternalEObject)deployment).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MultiClusterDslPackage.CLUSTER__DEPLOYMENT, null, msgs);
      if (newDeployment != null)
        msgs = ((InternalEObject)newDeployment).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MultiClusterDslPackage.CLUSTER__DEPLOYMENT, null, msgs);
      msgs = basicSetDeployment(newDeployment, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.CLUSTER__DEPLOYMENT, newDeployment, newDeployment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ingress getIngress()
  {
    return ingress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIngress(Ingress newIngress, NotificationChain msgs)
  {
    Ingress oldIngress = ingress;
    ingress = newIngress;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.CLUSTER__INGRESS, oldIngress, newIngress);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIngress(Ingress newIngress)
  {
    if (newIngress != ingress)
    {
      NotificationChain msgs = null;
      if (ingress != null)
        msgs = ((InternalEObject)ingress).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MultiClusterDslPackage.CLUSTER__INGRESS, null, msgs);
      if (newIngress != null)
        msgs = ((InternalEObject)newIngress).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MultiClusterDslPackage.CLUSTER__INGRESS, null, msgs);
      msgs = basicSetIngress(newIngress, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.CLUSTER__INGRESS, newIngress, newIngress));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.CLUSTER__DEPLOYMENT:
        return basicSetDeployment(null, msgs);
      case MultiClusterDslPackage.CLUSTER__INGRESS:
        return basicSetIngress(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.CLUSTER__NAME:
        return getName();
      case MultiClusterDslPackage.CLUSTER__DEPLOYMENT:
        return getDeployment();
      case MultiClusterDslPackage.CLUSTER__INGRESS:
        return getIngress();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.CLUSTER__NAME:
        setName((String)newValue);
        return;
      case MultiClusterDslPackage.CLUSTER__DEPLOYMENT:
        setDeployment((Deployment)newValue);
        return;
      case MultiClusterDslPackage.CLUSTER__INGRESS:
        setIngress((Ingress)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.CLUSTER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MultiClusterDslPackage.CLUSTER__DEPLOYMENT:
        setDeployment((Deployment)null);
        return;
      case MultiClusterDslPackage.CLUSTER__INGRESS:
        setIngress((Ingress)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.CLUSTER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MultiClusterDslPackage.CLUSTER__DEPLOYMENT:
        return deployment != null;
      case MultiClusterDslPackage.CLUSTER__INGRESS:
        return ingress != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ClusterImpl
