/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl.impl;

import multicluster.dsl.multiClusterDsl.Deployment;
import multicluster.dsl.multiClusterDsl.MultiClusterDslPackage;
import multicluster.dsl.multiClusterDsl.Resources;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Deployment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.DeploymentImpl#getImage <em>Image</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.DeploymentImpl#getReplicas <em>Replicas</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.DeploymentImpl#getResources <em>Resources</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeploymentImpl extends MinimalEObjectImpl.Container implements Deployment
{
  /**
   * The default value of the '{@link #getImage() <em>Image</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImage()
   * @generated
   * @ordered
   */
  protected static final String IMAGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getImage() <em>Image</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImage()
   * @generated
   * @ordered
   */
  protected String image = IMAGE_EDEFAULT;

  /**
   * The default value of the '{@link #getReplicas() <em>Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReplicas()
   * @generated
   * @ordered
   */
  protected static final int REPLICAS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getReplicas() <em>Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReplicas()
   * @generated
   * @ordered
   */
  protected int replicas = REPLICAS_EDEFAULT;

  /**
   * The cached value of the '{@link #getResources() <em>Resources</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResources()
   * @generated
   * @ordered
   */
  protected Resources resources;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeploymentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MultiClusterDslPackage.Literals.DEPLOYMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getImage()
  {
    return image;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setImage(String newImage)
  {
    String oldImage = image;
    image = newImage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.DEPLOYMENT__IMAGE, oldImage, image));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getReplicas()
  {
    return replicas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReplicas(int newReplicas)
  {
    int oldReplicas = replicas;
    replicas = newReplicas;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.DEPLOYMENT__REPLICAS, oldReplicas, replicas));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Resources getResources()
  {
    return resources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResources(Resources newResources, NotificationChain msgs)
  {
    Resources oldResources = resources;
    resources = newResources;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.DEPLOYMENT__RESOURCES, oldResources, newResources);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResources(Resources newResources)
  {
    if (newResources != resources)
    {
      NotificationChain msgs = null;
      if (resources != null)
        msgs = ((InternalEObject)resources).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MultiClusterDslPackage.DEPLOYMENT__RESOURCES, null, msgs);
      if (newResources != null)
        msgs = ((InternalEObject)newResources).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MultiClusterDslPackage.DEPLOYMENT__RESOURCES, null, msgs);
      msgs = basicSetResources(newResources, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.DEPLOYMENT__RESOURCES, newResources, newResources));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.DEPLOYMENT__RESOURCES:
        return basicSetResources(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.DEPLOYMENT__IMAGE:
        return getImage();
      case MultiClusterDslPackage.DEPLOYMENT__REPLICAS:
        return getReplicas();
      case MultiClusterDslPackage.DEPLOYMENT__RESOURCES:
        return getResources();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.DEPLOYMENT__IMAGE:
        setImage((String)newValue);
        return;
      case MultiClusterDslPackage.DEPLOYMENT__REPLICAS:
        setReplicas((Integer)newValue);
        return;
      case MultiClusterDslPackage.DEPLOYMENT__RESOURCES:
        setResources((Resources)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.DEPLOYMENT__IMAGE:
        setImage(IMAGE_EDEFAULT);
        return;
      case MultiClusterDslPackage.DEPLOYMENT__REPLICAS:
        setReplicas(REPLICAS_EDEFAULT);
        return;
      case MultiClusterDslPackage.DEPLOYMENT__RESOURCES:
        setResources((Resources)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.DEPLOYMENT__IMAGE:
        return IMAGE_EDEFAULT == null ? image != null : !IMAGE_EDEFAULT.equals(image);
      case MultiClusterDslPackage.DEPLOYMENT__REPLICAS:
        return replicas != REPLICAS_EDEFAULT;
      case MultiClusterDslPackage.DEPLOYMENT__RESOURCES:
        return resources != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (image: ");
    result.append(image);
    result.append(", replicas: ");
    result.append(replicas);
    result.append(')');
    return result.toString();
  }

} //DeploymentImpl
