/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl.impl;

import multicluster.dsl.multiClusterDsl.Health;
import multicluster.dsl.multiClusterDsl.MultiClusterDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Health</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.HealthImpl#getReadinessPath <em>Readiness Path</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.impl.HealthImpl#getLivenessPath <em>Liveness Path</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HealthImpl extends MinimalEObjectImpl.Container implements Health
{
  /**
   * The default value of the '{@link #getReadinessPath() <em>Readiness Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReadinessPath()
   * @generated
   * @ordered
   */
  protected static final String READINESS_PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReadinessPath() <em>Readiness Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReadinessPath()
   * @generated
   * @ordered
   */
  protected String readinessPath = READINESS_PATH_EDEFAULT;

  /**
   * The default value of the '{@link #getLivenessPath() <em>Liveness Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLivenessPath()
   * @generated
   * @ordered
   */
  protected static final String LIVENESS_PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLivenessPath() <em>Liveness Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLivenessPath()
   * @generated
   * @ordered
   */
  protected String livenessPath = LIVENESS_PATH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HealthImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MultiClusterDslPackage.Literals.HEALTH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getReadinessPath()
  {
    return readinessPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReadinessPath(String newReadinessPath)
  {
    String oldReadinessPath = readinessPath;
    readinessPath = newReadinessPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.HEALTH__READINESS_PATH, oldReadinessPath, readinessPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLivenessPath()
  {
    return livenessPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLivenessPath(String newLivenessPath)
  {
    String oldLivenessPath = livenessPath;
    livenessPath = newLivenessPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MultiClusterDslPackage.HEALTH__LIVENESS_PATH, oldLivenessPath, livenessPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.HEALTH__READINESS_PATH:
        return getReadinessPath();
      case MultiClusterDslPackage.HEALTH__LIVENESS_PATH:
        return getLivenessPath();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.HEALTH__READINESS_PATH:
        setReadinessPath((String)newValue);
        return;
      case MultiClusterDslPackage.HEALTH__LIVENESS_PATH:
        setLivenessPath((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.HEALTH__READINESS_PATH:
        setReadinessPath(READINESS_PATH_EDEFAULT);
        return;
      case MultiClusterDslPackage.HEALTH__LIVENESS_PATH:
        setLivenessPath(LIVENESS_PATH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MultiClusterDslPackage.HEALTH__READINESS_PATH:
        return READINESS_PATH_EDEFAULT == null ? readinessPath != null : !READINESS_PATH_EDEFAULT.equals(readinessPath);
      case MultiClusterDslPackage.HEALTH__LIVENESS_PATH:
        return LIVENESS_PATH_EDEFAULT == null ? livenessPath != null : !LIVENESS_PATH_EDEFAULT.equals(livenessPath);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (readinessPath: ");
    result.append(readinessPath);
    result.append(", livenessPath: ");
    result.append(livenessPath);
    result.append(')');
    return result.toString();
  }

} //HealthImpl
