/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMultiClusterDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(multicluster.dsl.multiClusterDsl.MultiClusterDslPackage.eINSTANCE);
		return result;
	}
}
