/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import multicluster.dsl.MultiClusterDslRuntimeModule;
import multicluster.dsl.MultiClusterDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MultiClusterDslIdeSetup extends MultiClusterDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MultiClusterDslRuntimeModule(), new MultiClusterDslIdeModule()));
	}
	
}
