/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class MultiClusterDslIdeModule extends AbstractMultiClusterDslIdeModule {
}
