/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.ui.tests;

import com.google.inject.Injector;
import multicluster.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MultiClusterDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("multicluster.dsl.MultiClusterDsl");
	}

}
