/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MultiClusterDslProposalProvider extends AbstractMultiClusterDslProposalProvider {
}
