/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Application#getName <em>Name</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Application#getClusters <em>Clusters</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getApplication()
 * @model
 * @generated
 */
public interface Application extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getApplication_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Application#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Clusters</b></em>' containment reference list.
   * The list contents are of type {@link multicluster.dsl.multiClusterDsl.Cluster}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clusters</em>' containment reference list.
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getApplication_Clusters()
   * @model containment="true"
   * @generated
   */
  EList<Cluster> getClusters();

} // Application
