/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Auto Scaling</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.AutoScaling#getMinReplicas <em>Min Replicas</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.AutoScaling#getMaxReplicas <em>Max Replicas</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.AutoScaling#getCpuUtilization <em>Cpu Utilization</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getAutoScaling()
 * @model
 * @generated
 */
public interface AutoScaling extends EObject
{
  /**
   * Returns the value of the '<em><b>Min Replicas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Replicas</em>' attribute.
   * @see #setMinReplicas(int)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getAutoScaling_MinReplicas()
   * @model
   * @generated
   */
  int getMinReplicas();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.AutoScaling#getMinReplicas <em>Min Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Replicas</em>' attribute.
   * @see #getMinReplicas()
   * @generated
   */
  void setMinReplicas(int value);

  /**
   * Returns the value of the '<em><b>Max Replicas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Replicas</em>' attribute.
   * @see #setMaxReplicas(int)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getAutoScaling_MaxReplicas()
   * @model
   * @generated
   */
  int getMaxReplicas();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.AutoScaling#getMaxReplicas <em>Max Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Replicas</em>' attribute.
   * @see #getMaxReplicas()
   * @generated
   */
  void setMaxReplicas(int value);

  /**
   * Returns the value of the '<em><b>Cpu Utilization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cpu Utilization</em>' attribute.
   * @see #setCpuUtilization(int)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getAutoScaling_CpuUtilization()
   * @model
   * @generated
   */
  int getCpuUtilization();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.AutoScaling#getCpuUtilization <em>Cpu Utilization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cpu Utilization</em>' attribute.
   * @see #getCpuUtilization()
   * @generated
   */
  void setCpuUtilization(int value);

} // AutoScaling
