/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cluster</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Cluster#getName <em>Name</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Cluster#getDeployment <em>Deployment</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Cluster#getIngress <em>Ingress</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getCluster()
 * @model
 * @generated
 */
public interface Cluster extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getCluster_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Cluster#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Deployment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deployment</em>' containment reference.
   * @see #setDeployment(Deployment)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getCluster_Deployment()
   * @model containment="true"
   * @generated
   */
  Deployment getDeployment();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Cluster#getDeployment <em>Deployment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deployment</em>' containment reference.
   * @see #getDeployment()
   * @generated
   */
  void setDeployment(Deployment value);

  /**
   * Returns the value of the '<em><b>Ingress</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ingress</em>' containment reference.
   * @see #setIngress(Ingress)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getCluster_Ingress()
   * @model containment="true"
   * @generated
   */
  Ingress getIngress();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Cluster#getIngress <em>Ingress</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ingress</em>' containment reference.
   * @see #getIngress()
   * @generated
   */
  void setIngress(Ingress value);

} // Cluster
