/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.ConfigMap#getName <em>Name</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.ConfigMap#getEntries <em>Entries</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getConfigMap()
 * @model
 * @generated
 */
public interface ConfigMap extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getConfigMap_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.ConfigMap#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entries</b></em>' containment reference list.
   * The list contents are of type {@link multicluster.dsl.multiClusterDsl.ConfigEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' containment reference list.
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getConfigMap_Entries()
   * @model containment="true"
   * @generated
   */
  EList<ConfigEntry> getEntries();

} // ConfigMap
