/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.ConfigEntry#getKey <em>Key</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.ConfigEntry#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getConfigEntry()
 * @model
 * @generated
 */
public interface ConfigEntry extends EObject
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getConfigEntry_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.ConfigEntry#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getConfigEntry_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.ConfigEntry#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // ConfigEntry
