/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deployment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Deployment#getImage <em>Image</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Deployment#getReplicas <em>Replicas</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Deployment#getResources <em>Resources</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Deployment#getHealth <em>Health</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getDeployment()
 * @model
 * @generated
 */
public interface Deployment extends EObject
{
  /**
   * Returns the value of the '<em><b>Image</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image</em>' attribute.
   * @see #setImage(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getDeployment_Image()
   * @model
   * @generated
   */
  String getImage();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Deployment#getImage <em>Image</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image</em>' attribute.
   * @see #getImage()
   * @generated
   */
  void setImage(String value);

  /**
   * Returns the value of the '<em><b>Replicas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Replicas</em>' attribute.
   * @see #setReplicas(int)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getDeployment_Replicas()
   * @model
   * @generated
   */
  int getReplicas();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Deployment#getReplicas <em>Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Replicas</em>' attribute.
   * @see #getReplicas()
   * @generated
   */
  void setReplicas(int value);

  /**
   * Returns the value of the '<em><b>Resources</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resources</em>' containment reference.
   * @see #setResources(Resources)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getDeployment_Resources()
   * @model containment="true"
   * @generated
   */
  Resources getResources();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Deployment#getResources <em>Resources</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resources</em>' containment reference.
   * @see #getResources()
   * @generated
   */
  void setResources(Resources value);

  /**
   * Returns the value of the '<em><b>Health</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Health</em>' containment reference.
   * @see #setHealth(Health)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getDeployment_Health()
   * @model containment="true"
   * @generated
   */
  Health getHealth();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Deployment#getHealth <em>Health</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Health</em>' containment reference.
   * @see #getHealth()
   * @generated
   */
  void setHealth(Health value);

} // Deployment
