/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Health</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Health#getReadinessPath <em>Readiness Path</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Health#getLivenessPath <em>Liveness Path</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getHealth()
 * @model
 * @generated
 */
public interface Health extends EObject
{
  /**
   * Returns the value of the '<em><b>Readiness Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Readiness Path</em>' attribute.
   * @see #setReadinessPath(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getHealth_ReadinessPath()
   * @model
   * @generated
   */
  String getReadinessPath();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Health#getReadinessPath <em>Readiness Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Readiness Path</em>' attribute.
   * @see #getReadinessPath()
   * @generated
   */
  void setReadinessPath(String value);

  /**
   * Returns the value of the '<em><b>Liveness Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liveness Path</em>' attribute.
   * @see #setLivenessPath(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getHealth_LivenessPath()
   * @model
   * @generated
   */
  String getLivenessPath();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Health#getLivenessPath <em>Liveness Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Liveness Path</em>' attribute.
   * @see #getLivenessPath()
   * @generated
   */
  void setLivenessPath(String value);

} // Health
