/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resources</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Resources#getCpu <em>Cpu</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Resources#getMemory <em>Memory</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getResources()
 * @model
 * @generated
 */
public interface Resources extends EObject
{
  /**
   * Returns the value of the '<em><b>Cpu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cpu</em>' attribute.
   * @see #setCpu(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getResources_Cpu()
   * @model
   * @generated
   */
  String getCpu();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Resources#getCpu <em>Cpu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cpu</em>' attribute.
   * @see #getCpu()
   * @generated
   */
  void setCpu(String value);

  /**
   * Returns the value of the '<em><b>Memory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Memory</em>' attribute.
   * @see #setMemory(String)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getResources_Memory()
   * @model
   * @generated
   */
  String getMemory();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Resources#getMemory <em>Memory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Memory</em>' attribute.
   * @see #getMemory()
   * @generated
   */
  void setMemory(String value);

} // Resources
