/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Service</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Service#getType <em>Type</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Service#getPort <em>Port</em>}</li>
 *   <li>{@link multicluster.dsl.multiClusterDsl.Service#getTargetPort <em>Target Port</em>}</li>
 * </ul>
 *
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getService()
 * @model
 * @generated
 */
public interface Service extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link multicluster.dsl.multiClusterDsl.ServiceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see multicluster.dsl.multiClusterDsl.ServiceType
   * @see #setType(ServiceType)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getService_Type()
   * @model
   * @generated
   */
  ServiceType getType();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Service#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see multicluster.dsl.multiClusterDsl.ServiceType
   * @see #getType()
   * @generated
   */
  void setType(ServiceType value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getService_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Service#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Target Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Port</em>' attribute.
   * @see #setTargetPort(int)
   * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage#getService_TargetPort()
   * @model
   * @generated
   */
  int getTargetPort();

  /**
   * Sets the value of the '{@link multicluster.dsl.multiClusterDsl.Service#getTargetPort <em>Target Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Port</em>' attribute.
   * @see #getTargetPort()
   * @generated
   */
  void setTargetPort(int value);

} // Service
