/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import multicluster.dsl.multiClusterDsl.Application;
import multicluster.dsl.multiClusterDsl.Cluster;
import multicluster.dsl.multiClusterDsl.Deployment;
import multicluster.dsl.multiClusterDsl.Ingress;
import multicluster.dsl.multiClusterDsl.Model;
import multicluster.dsl.multiClusterDsl.MultiClusterDslPackage;
import multicluster.dsl.multiClusterDsl.Resources;
import multicluster.dsl.services.MultiClusterDslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class MultiClusterDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MultiClusterDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MultiClusterDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MultiClusterDslPackage.APPLICATION:
				sequence_Application(context, (Application) semanticObject); 
				return; 
			case MultiClusterDslPackage.CLUSTER:
				sequence_Cluster(context, (Cluster) semanticObject); 
				return; 
			case MultiClusterDslPackage.DEPLOYMENT:
				sequence_Deployment(context, (Deployment) semanticObject); 
				return; 
			case MultiClusterDslPackage.INGRESS:
				sequence_Ingress(context, (Ingress) semanticObject); 
				return; 
			case MultiClusterDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case MultiClusterDslPackage.RESOURCES:
				sequence_Resources(context, (Resources) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Application returns Application
	 *
	 * Constraint:
	 *     (name=ID clusters+=Cluster*)
	 * </pre>
	 */
	protected void sequence_Application(ISerializationContext context, Application semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Cluster returns Cluster
	 *
	 * Constraint:
	 *     (name=ID deployment=Deployment ingress=Ingress?)
	 * </pre>
	 */
	protected void sequence_Cluster(ISerializationContext context, Cluster semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Deployment returns Deployment
	 *
	 * Constraint:
	 *     (image=STRING replicas=INT resources=Resources)
	 * </pre>
	 */
	protected void sequence_Deployment(ISerializationContext context, Deployment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MultiClusterDslPackage.Literals.DEPLOYMENT__IMAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MultiClusterDslPackage.Literals.DEPLOYMENT__IMAGE));
			if (transientValues.isValueTransient(semanticObject, MultiClusterDslPackage.Literals.DEPLOYMENT__REPLICAS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MultiClusterDslPackage.Literals.DEPLOYMENT__REPLICAS));
			if (transientValues.isValueTransient(semanticObject, MultiClusterDslPackage.Literals.DEPLOYMENT__RESOURCES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MultiClusterDslPackage.Literals.DEPLOYMENT__RESOURCES));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDeploymentAccess().getImageSTRINGTerminalRuleCall_3_0(), semanticObject.getImage());
		feeder.accept(grammarAccess.getDeploymentAccess().getReplicasINTTerminalRuleCall_5_0(), semanticObject.getReplicas());
		feeder.accept(grammarAccess.getDeploymentAccess().getResourcesResourcesParserRuleCall_6_0(), semanticObject.getResources());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Ingress returns Ingress
	 *
	 * Constraint:
	 *     path=STRING
	 * </pre>
	 */
	protected void sequence_Ingress(ISerializationContext context, Ingress semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MultiClusterDslPackage.Literals.INGRESS__PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MultiClusterDslPackage.Literals.INGRESS__PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIngressAccess().getPathSTRINGTerminalRuleCall_3_0(), semanticObject.getPath());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     application=Application
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MultiClusterDslPackage.Literals.MODEL__APPLICATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MultiClusterDslPackage.Literals.MODEL__APPLICATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getModelAccess().getApplicationApplicationParserRuleCall_0(), semanticObject.getApplication());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Resources returns Resources
	 *
	 * Constraint:
	 *     (cpu=STRING memory=STRING)
	 * </pre>
	 */
	protected void sequence_Resources(ISerializationContext context, Resources semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MultiClusterDslPackage.Literals.RESOURCES__CPU) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MultiClusterDslPackage.Literals.RESOURCES__CPU));
			if (transientValues.isValueTransient(semanticObject, MultiClusterDslPackage.Literals.RESOURCES__MEMORY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MultiClusterDslPackage.Literals.RESOURCES__MEMORY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getResourcesAccess().getCpuSTRINGTerminalRuleCall_3_0(), semanticObject.getCpu());
		feeder.accept(grammarAccess.getResourcesAccess().getMemorySTRINGTerminalRuleCall_5_0(), semanticObject.getMemory());
		feeder.finish();
	}
	
	
}
