/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MultiClusterDslStandaloneSetup extends MultiClusterDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MultiClusterDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
