/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MultiClusterDslRuntimeModule extends AbstractMultiClusterDslRuntimeModule {
}
