///*
// * generated by Xtext 2.36.0
// */
//package multicluster.dsl;
//
//
///**
// * Use this class to register components to be used at runtime / without the Equinox extension registry.
// */
//public class MultiClusterDslRuntimeModule extends AbstractMultiClusterDslRuntimeModule {
//}

/* 

 * generated by Xtext 2.36.0 

 */ 

package multicluster.dsl; 

 

import org.eclipse.xtext.generator.IGenerator2; 

import multicluster.dsl.generator.MultiClusterDslGenerator; 

 

 

/** 

 * Use this class to register components to be used at runtime / without the Equinox extension registry. 

 */ 

public class MultiClusterDslRuntimeModule extends AbstractMultiClusterDslRuntimeModule { 

 

    @Override 

    public Class<? extends IGenerator2> bindIGenerator2() { 

    return MultiClusterDslGenerator.class; 

 

    } 

} 
