/**
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.multiClusterDsl.util;

import multicluster.dsl.multiClusterDsl.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see multicluster.dsl.multiClusterDsl.MultiClusterDslPackage
 * @generated
 */
public class MultiClusterDslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MultiClusterDslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MultiClusterDslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = MultiClusterDslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiClusterDslSwitch<Adapter> modelSwitch =
    new MultiClusterDslSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseApplication(Application object)
      {
        return createApplicationAdapter();
      }
      @Override
      public Adapter caseCluster(Cluster object)
      {
        return createClusterAdapter();
      }
      @Override
      public Adapter caseDeployment(Deployment object)
      {
        return createDeploymentAdapter();
      }
      @Override
      public Adapter caseResources(Resources object)
      {
        return createResourcesAdapter();
      }
      @Override
      public Adapter caseHealth(Health object)
      {
        return createHealthAdapter();
      }
      @Override
      public Adapter caseService(Service object)
      {
        return createServiceAdapter();
      }
      @Override
      public Adapter caseIngress(Ingress object)
      {
        return createIngressAdapter();
      }
      @Override
      public Adapter caseConfigMap(ConfigMap object)
      {
        return createConfigMapAdapter();
      }
      @Override
      public Adapter caseConfigEntry(ConfigEntry object)
      {
        return createConfigEntryAdapter();
      }
      @Override
      public Adapter caseAutoScaling(AutoScaling object)
      {
        return createAutoScalingAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Application <em>Application</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Application
   * @generated
   */
  public Adapter createApplicationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Cluster <em>Cluster</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Cluster
   * @generated
   */
  public Adapter createClusterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Deployment <em>Deployment</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Deployment
   * @generated
   */
  public Adapter createDeploymentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Resources <em>Resources</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Resources
   * @generated
   */
  public Adapter createResourcesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Health <em>Health</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Health
   * @generated
   */
  public Adapter createHealthAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Service <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Service
   * @generated
   */
  public Adapter createServiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.Ingress <em>Ingress</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.Ingress
   * @generated
   */
  public Adapter createIngressAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.ConfigMap <em>Config Map</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.ConfigMap
   * @generated
   */
  public Adapter createConfigMapAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.ConfigEntry <em>Config Entry</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.ConfigEntry
   * @generated
   */
  public Adapter createConfigEntryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link multicluster.dsl.multiClusterDsl.AutoScaling <em>Auto Scaling</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see multicluster.dsl.multiClusterDsl.AutoScaling
   * @generated
   */
  public Adapter createAutoScalingAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //MultiClusterDslAdapterFactory
