//Ai output: 

Namespace 

apiVersion: v1 

kind: Namespace 

metadata: 

  name: prod 

 

//DEV Deployment 

apiVersion: apps/v1 

kind: Deployment 

metadata: 

  name: backendapi-dev 

  namespace: prod 

spec: 

  replicas: 1 

  selector: 

    matchLabels: 

      app: backendapi 

      env: dev 

  template: 

    metadata: 

      labels: 

        app: backendapi 

        env: dev 

    spec: 

      containers: 

        - name: backend 

          image: backend:latest 

          resources: 

            requests: 

              cpu: "250m" 

              memory: "256Mi" 

            limits: 

              cpu: "250m" 

              memory: "256Mi" 

 

//STAGING Deployment 

apiVersion: apps/v1 

kind: Deployment 

metadata: 

  name: backendapi-staging 

  namespace: prod 

spec: 

  replicas: 2 

  selector: 

    matchLabels: 

      app: backendapi 

      env: staging 

  template: 

    metadata: 

      labels: 

        app: backendapi 

        env: staging 

    spec: 

      containers: 

        - name: backend 

          image: backend:latest 

          resources: 

            requests: 

              cpu: "500m" 

              memory: "512Mi" 

            limits: 

              cpu: "500m" 

              memory: "512Mi" 

 

//PRODUCTION Deployment 

apiVersion: apps/v1 

kind: Deployment 

metadata: 

  name: backendapi-prod 

  namespace: prod 

spec: 

  replicas: 5 

  selector: 

    matchLabels: 

      app: backendapi 

      env: production 

  template: 

    metadata: 

      labels: 

        app: backendapi 

        env: production 

    spec: 

      containers: 

        - name: backend 

          image: backend:latest 

          ports: 

            - containerPort: 8080 

          resources: 

            requests: 

              cpu: "1000m" 

              memory: "1Gi" 

            limits: 

              cpu: "1000m" 

              memory: "1Gi" 

          readinessProbe: 

            httpGet: 

              path: /ready 

              port: 8080 

          livenessProbe: 

            httpGet: 

              path: /health 

              port: 8080 

 

//PRODUCTION Service 

apiVersion: v1 

kind: Service 

metadata: 

  name: backendapi-prod-service 

  namespace: prod 

spec: 

  type: LoadBalancer 

  selector: 

    app: backendapi 

    env: production 

  ports: 

    - port: 80 

      targetPort: 8080 
 

//PRODUCTION Ingress 

apiVersion: networking.k8s.io/v1 

kind: Ingress 

metadata: 

  name: backendapi-prod-ingress 

  namespace: prod 

spec: 

  rules: 

    - http: 

        paths: 

          - path: /api 

            pathType: Prefix 

            backend: 

              service: 

                name: backendapi-prod-service 

                port: 

                  number: 80 

 

//PRODUCTION Horizontal Pod Autoscaler 

apiVersion: autoscaling/v2 

kind: HorizontalPodAutoscaler 

metadata: 

  name: backendapi-prod-hpa 

  namespace: prod 

spec: 

  scaleTargetRef: 

    apiVersion: apps/v1 

    kind: Deployment 

    name: backendapi-prod 

  minReplicas: 3 

  maxReplicas: 6 

  metrics: 

    - type: Resource 

      resource: 

        name: cpu 

        target: 

          type: Utilization 

          averageUtilization: 70
