/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MultiClusterDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("multicluster/dsl/parser/antlr/internal/InternalMultiClusterDsl.tokens");
	}
}
