/*
 * generated by Xtext 2.36.0
 */
package multicluster.dsl.parser.antlr;

import com.google.inject.Inject;
import multicluster.dsl.parser.antlr.internal.InternalMultiClusterDslParser;
import multicluster.dsl.services.MultiClusterDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MultiClusterDslParser extends AbstractAntlrParser {

	@Inject
	private MultiClusterDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMultiClusterDslParser createParser(XtextTokenStream stream) {
		return new InternalMultiClusterDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MultiClusterDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MultiClusterDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
